/* global proc xcam01()

    creates a camera from DLT calibration in XrayProject or from XMA Lab
    
    User selects a *mayacam.csv file (from DLT calibration in XrayProject
    User selects an image or image sequence by selecting the first file in the sequence
    User selects a camera name
    requires _getShape.mel
    
    Written by David Baier 
    last updated: 8/25/2015
*/ 
global proc xcam01()
{
    xcam02(2);
}



    